### ISSUE TITLE
Addition of EQU and SAC segments

### ISSUE THREAD

**Issue by mmonahanfl** [senaranya/HL7#18]
I have written the code for this if you want them.  These segments are used in SSU messages.

**Comment by senaranya** [comment]
I'd love to, please create a pull request

**Comment by mmonahanfl** [comment]
Forgive me if I missed something 'obvious'.  I haven't contributed to a github open source project yet.

When I try to push the branch, I am getting:
remote: Permission to senaranya/HL7.git denied to mmonahanfl.

________________________________

**Comment by senaranya** [comment]
You won't be able to directly push the branch to the repo. You'll have to 
a) Fork the repo, which creates a copy of the repository on your account
b) Clone the forked one instead of mine
c) Create a branch, push your changes
d) Now when you visit your copy of the repo on GitHub, there'll be a button 'Compare and Pull Request'. Use that to create a 'PR', which I'll review and merge

It's slightly complicated for new GitHub contributors (myself included). I suggest you watch some tutorial on YouTube, in case if I've missed something

**Comment by senaranya** [comment]
Thank you so much for your contribution
