### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by pluk77** [senaranya/HL7#50]
I see the php version requirements have been updated and 7.2 has been removed. What is the reason for this, as it looks like there  does not seem to be code that is not able to run on 7.2. 

Would you be open to adding a new branch / version that continues with PHP 7.2 where patches can be ported to keep those using your library with 7.2 at least up to date with bug fixes?

**Comment by senaranya** [comment]
Here are the reasons:
* Stay up to date with dependencies (e.g., PHPUnit 9 runs only on PHP 7.3+)
* Ability to use updated language features. Even if some features are not used now, we're highly likely to use those in coming versions
* Some of the extension (e.g. socket) behavior changed from 7.2 to 7.3. Since sockets are used in Connection class, it's not backward compatible
* PHP 7.2 usage is going down (Ref: [Charts](https://blog.packagist.com/php-versions-stats-2021-1-edition/)), so at this point it's decided to abandon it in favor of more modern versions. 

Since the user base for this package are mostly on PHP 7.3+, it won't be worth the effort maintaining it for 7.2. However, if I find enough requests for it, I'll definitely consider it.
